# Generated by Django 3.0.4 on 2020-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('dec', models.TextField()),
                ('capacity', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('annualtraffic', models.IntegerField()),
                ('datetraffic', models.DateField()),
                ('introYear', models.CharField(max_length=4)),
                ('containers', models.IntegerField()),
                ('mobileBodies', models.IntegerField()),
                ('unaccompaniedTrailers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
