# Generated by Django 3.0.4 on 2020-04-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200420_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='port',
            name='introYear',
        ),
        migrations.RemoveField(
            model_name='port',
            name='mobileBodies',
        ),
        migrations.RemoveField(
            model_name='port',
            name='unaccompaniedTrailers',
        ),
    ]
